### ISSUE TITLE
TTN Socket

### ISSUE THREAD

**Issue by renatocarusos** [jgromes/LoRaLib#33]
**Hi, Jan**
You plan to implement a socket to connect to the TTN (The Things Network). I started to investigate how to implement this connection, but I think it will be easier for you to do. Already in your plans with this library?

**Comment by jgromes** [comment]
Not in LoRaLib - I want to keep this library just as a control for SX127x series LoRa chips. I did however investigate implementing LoRaWAN support in KiteLib, since that already has means to separate protocol implementation from the communication module (e.g. MQTT and HTTP protocols over ESP8266). If at some point I implement LoRaWAN or TTN, it will be in KiteLib, not here.
