### ISSUE TITLE
No packet received on receiver LoRa-02 . Everything worked perfectly fine before

### ISSUE THREAD

**Issue by Benedict-Bsl** [jgromes/LoRaLib#94]
![Interfacing-SX1278-LoRa-Module-with-Arduino](https://user-images.githubusercontent.com/28983044/69829946-52341b00-1233-11ea-806b-39926f70aeb7.jpg)

I am using the above lora module and the same connection with the example codes found in this interesting library(LoRALib by jgromes); with the "Transmit" and "Received" code provided. It was working perfectly fine before, but a few days ago, it is just stack at "Waiting for incoming transmission..." block. And it goes no further, while the receiver is actually sending real time data and all. 

Your help will greatly be appreciated. Thanks.

**Comment by jgromes** [comment]
Seeing as you have the exact same issue using a different library (https://github.com/sandeepmistry/arduino-LoRa/issues/307), I suspect this is most likely a hardware issue, either on receiver, on transmitter, or both - though you haven't provided nearly enough information to even take a guess at what could be the cause

Assuming the photo is your actual setup, I doubt it will work long-term - Arduino Nano in that picture is connected directly to the LoRa module without any sort of logic level shift. Since Arduino Nano has 5V logic and SX127x modules have 3.3V logic, the LoRa module will get damaged eventually.

**Comment by Benedict-Bsl** [comment]
I had the same problem with a different library, so i decided to use yours, i eventually ended up with the same issue. 
i have connected the LoRa module (as you can seen in the picture) to a LM317T regulator which outputs a voltage of 3.34V.

**Comment by jgromes** [comment]
The supply voltage and logic voltage level are not the same: Arduino Nano outputs 5V signals. Those are connected directly to the LoRa module, which only has 3.3V inputs. This might work for some time, but eventually, the module will get damaged - exactly what seems to have happened in your case.

**Comment by Benedict-Bsl** [comment]
I see what you mean. Any suggestions please? (never done that before to be honest).

**Comment by Benedict-Bsl** [comment]
It will be of great help. Thank you.

**Comment by Benedict-Bsl** [comment]
Can these 4 Channel Bi-Directional Logic Level Shifter Converter 3.3V-5V Logics Level Converter do the work?

**Comment by jgromes** [comment]
Almost any shifter should do here, something like this will probably be fine: https://learn.sparkfun.com/tutorials/bi-directional-logic-level-converter-hookup-guide/all

Alternatively, you could use 3.3V Arduino board. And you should probably change the LoRa module as well, hard to guess what exactly is broken with the current one.

Also, you should probably use RadioLib instead of LoRaLib if you want long term support, since LoRaLib will be discontinued on the near future.

**Comment by Benedict-Bsl** [comment]
Thank you so much. I bought one of these a long time ago, and i never thought of using them. Thank you so much again.
